### PR TITLE
Add a mixin for clearfixes

### LINKED ISSUE #30: Separate clearfix to its own mixin
Just a proposal to set basic `::after` clearfix into its own mixin.

## Expected Behavior
Clearfixes should be standardized and reused.

## Current Behavior
Clearfixes are rewritten in every place where they are needed.

## Context (Environment)
I was confused when I learned that there currently is no clearfix mixin.

## Possible Solution
Refer to the PR following.

### PR DESCRIPTION
**Pull request by akselinurmio**
This PR fixes #30 by adding a new mixin called `clearfix`. It doesn't change any functionalities in the resulting CSS, merely moves some of the clearfixes to the top of the declaration block tree. This shouldn't do anything bad.

## Motivation and Context
Made with simplicity and code reusing in mind. No functionality changes.

## How Has This Been Tested?
Present in RuokaTutka project, which is live at https://ruokatutka.em87.io/ . Everything works.

### CODE REVIEW

**Comment by juhalehtonen** [comment]
I can't recall the last time I even used a clearfix, but I agree that having the clearfix encapsulated in one place is better than having them scattered all over :) 

However, I would suggest adding an option to choose between before- and after- pseudoelements, as sometimes you'll already have one in use and don't want to override it by using the mixin.

**Comment by akselinurmio** [comment]
I also pondered over pros and cons of adding a new mixin, but came to a conclusion that because the clearfix is so commonly known piece of reused code, it may be better to maintain it separately.

The `::before` – `::after` choice is also a valid point. I'm adding it right now.

**Comment by akselinurmio** [comment]
Updated now, @juhalehtonen.

**Comment by peksipatongeis** [comment]
bootstrap-sass is part of Swiss and it has a clearfix mixin included so there's no need to add this.

As a side note, I don't think you can use before element for clearfixes in any sensible way. I might be wrong with this tho.

**Comment by juhalehtonen** [comment]
@peksipatongeis is right about that, I realized it too right after commenting but never realized to correct myself :D The clearfix depends on the document flow so ::before doesn't work.

**Comment by akselinurmio** [comment]
I guess what we would really want to do is to get rid of the remaining Bootstrap dependency. In the meantime I don't think it matters which mixin we use, but if we are going to ditch Bootstrap, this is the way to go.

What do you think?

**Comment by akselinurmio** [comment]
Closing ":D"

**Pull request closed without merging**
